baseurl: / #sola-analytics.com
languageCode: en-us
title: Sola Analytics
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: 
      url: https://github.com/gaelso
      pre: "<i class='fab fa-github fa-lg'></i>"
    - name: 
      url: https://www.linkedin.com/in/gaelsola/)
      pre: "<i class='fab fa-linkedin fa-lg'  color:#0a66c2; ></i>"
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  # favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 60
    url: logo-600px-name.svg
    width: 160
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
