baseurl: / #sola-analytics.com
languageCode: en-us
title: Sola Analytics
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      identifier: about
      url: /about/
      pre: ""
      weight: 1
    - name: Blog
      identifier: blog
      url: /blog/
      pre: ""
      weight: 2
    - name: Projects
      identifier: projects 
      url: /projects/
      pre: ""
      weight: 3
    - name: Training
      identifier: training
      url: /training/
      weight: 4
    - name: 
      identifier: github
      url: https://github.com/gaelso
      pre: "<i class='fa-brands fa-github fa-lg'></i><i class='fa-solid fa-arrow-up-right-from-square fa-2xs'></i>" 
      weight: 10
    - name: 
      identifier: linkedin
      url: https://www.linkedin.com/in/gaelsola/
      pre: "<i class='fa-brands fa-linkedin fa-lg'></i>"
      weight: 11
    - name: 
      identifier: email
      url: mailto:gael.sola@sola-analytics.com
      pre: "<i class='fa-solid fa-envelope fa-lg'></i>"
      weight: 12
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  # favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 60
    #url: logo-600px-name.svg # logo-60px-full.png
    width: 160
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
